### ISSUE TITLE
Trickster returns errors when the system clock is behind

### ISSUE THREAD

**Issue by jranson** [Comcast/trickster#109]
In places like https://github.com/Comcast/trickster/blob/master/handlers.go#L930 we are using "now" (based on the system clock) as part of deterministically adjusting start/end times. We probably should not do this. When the system clock is behind (e.g., ntp is not configured, a developer's laptop has the date set wrong, etc), this can unintentionally truncate data on the right of the graph. Further, when the system clock is _significantly_ behind, this logic is putting the end time before the start time and causing Trickster to return a 400 error.   @jacksontj

**Comment by jacksontj** [comment]
Prometheus itself actually has this same problem, which is why it has a warning banner on the UI that tells you about the issue. In reality there's not a great way of dealing with this, since this is a timeseries API (so time matters). If you don't have the fast-forward option enabled we could *not* touch the time and just pass it through, but in the case of fast-forward there isn't much to do :/

**Comment by jranson** [comment]
Yep, definitely agree on the Fast Forward feature.

 The line that I referenced above is in alignStepBoundaries, which is unrelated to Fast Forward, and affects queries even with FF Disabled.

**Comment by jranson** [comment]
One option we have is to use the `Date` header on the upstream prometheus's response to help with bad local clocks. I will take a look at the feasibility of this and see if it's something that would be beneficial.

**Comment by SuperQ** [comment]
We added a browser warning in the Prometheus console to tell users that their clock is off. Maybe we should add the same kind of warning to Grafana.

**Comment by FUSAKLA** [comment]
This would be great to see the same warning in Grafana.

**Comment by jranson** [comment]
@SuperQ just to clarify - are you warning in Prom when the _browser user's_ clock is off? The issue I am finding here is when the host running Trickster has a clock issue.

**Comment by SuperQ** [comment]
@jranson Yes, we have a little javascript warning that the browser clock differs from the server clock.
