### ISSUE TITLE
query_range no longer returns the full merged data set

### ISSUE THREAD

**Issue by yosifkit** [Comcast/trickster#116]
Using local build from master (646440f678b8e33b23412f8645faf58fe8a6ff46).

1. setup new trickster with copy of `example.conf` with an appropriate prometheus url
1. query prometheus graph via proxy web interface to fill up its cache
   1. first fetch returns a full set of data (~250 data points)
1. wait for scraping to make more data and execute again
   1. trickster only returns points newer than what was on the graph (~3 data points)
   1. graph is empty except for the last couple points

When using a build from the `0.1.5` tag, it works as expected and all data is returned. As far as I can tell, it seems #114 would be the cause since not much else has changed in master since `0.1.5`.

Thanks and I hope this helps!

**Comment by sylr** [comment]
I also noticed something that sounds like you described https://github.com/Comcast/trickster/issues/92#issuecomment-449025630

**Comment by sylr** [comment]
cc @jacksontj

**Comment by jacksontj** [comment]
@sylr thanks for the cc -- I was able to repro this locally and have a fix up in #117. This is a bit concerning as this breaks pretty fundamental usage and there were no test failures, which basically destroys any trust I had in the tests to begin with :/
