### ISSUE TITLE
MemLeak on Reap on Redis and BoltDB

### ISSUE THREAD

**Issue by R4scal** [Comcast/trickster#128]
Hi
Trickster periodically crahes when use redis as cache

```
trickster --version
0.1.7
```

```
trickster[40267]: panic: runtime error: index out of range
trickster[40267]: goroutine 38 [running]:
trickster[40267]: main.(*RedisCache).ReapOnce(0xc0001a6700)
trickster[40267]: #011/Users/jranso000/code/go/src/github.com/Comcast/trickster/redis.go:84 +0x6e7
trickster[40267]: main.(*RedisCache).Reap(0xc0001a6700)
trickster[40267]: #011/Users/jranso000/code/go/src/github.com/Comcast/trickster/redis.go:61 +0x2b
trickster[40267]: created by main.(*RedisCache).Connect
trickster[40267]: #011/Users/jranso000/code/go/src/github.com/Comcast/trickster/redis.go:42 +0x241
```

**Comment by R4scal** [comment]
After some times ago I can say, that redis cache in trickster is a very inefficient. I was switch cache type from redis to boltdb, and server resources utilisation dramatically changed:
<img width="726" alt="screenshot 2019-02-16 at 21 54 21" src="https://user-images.githubusercontent.com/16123585/52903922-bf8f3600-3235-11e9-887e-62975c5eeb69.png">
<img width="606" alt="screenshot 2019-02-16 at 21 54 33" src="https://user-images.githubusercontent.com/16123585/52903923-c453ea00-3235-11e9-8c9d-86f61c95d834.png">
<img width="668" alt="screenshot 2019-02-16 at 21 55 28" src="https://user-images.githubusercontent.com/16123585/52903926-c6b64400-3235-11e9-8a2d-425a2c4a5aff.png">

**Comment by R4scal** [comment]
@And after some times I have 300Mb boltdb file and frequently killed by OOM trickster
<img width="665" alt="screenshot 2019-02-18 at 09 14 05" src="https://user-images.githubusercontent.com/16123585/52931513-b7321a80-335d-11e9-9826-7abfb0a6f44f.png">
<img width="668" alt="screenshot 2019-02-18 at 09 14 13" src="https://user-images.githubusercontent.com/16123585/52931519-ba2d0b00-335d-11e9-93cc-313d3c29693f.png">

**Comment by jranson** [comment]
All of the reports for this issue are related to the legacy codebase and releases which, as of today, are no longer supported. If you are experiencing this issue in Trickster 1.0, let's open a new issue.
