### ISSUE TITLE
Handle Cache Control Headers

### ISSUE THREAD

**Issue by jranson** [Comcast/trickster#143]
For Full Object Caching we should support upstream Cache Control headers (`Expiration`, `Cache-Control` (no-cache, max-age), and `Pragma: no-cache`) when present.

**Comment by IKSIN** [comment]
Hello! Have you any updates?

**Comment by jranson** [comment]
Hi @IKSIN, so we have merged a large chunk of this issue into `next`, which means it will be in the next beta release. Beta 10 is currently overdue, as we are making some final internal quality fixes, but we should have it released by the end of the year. Thanks for checking, we're really excited to share this with everyone!

**Comment by IKSIN** [comment]
@jranson Thanks) And what about handling cache-control headers from trickster backend in delta-proxy? We need to no caching policy for some cases. We use `thanos`, and i want to add `no-cache` headers on partial response.

**Comment by jranson** [comment]
@IKSIN we finally have that new release out, and it does support the proper observance of all cache control headers, including in the timeseries delta proxy. So any headers you send down from Thanos should be respected. Please reopen if you have any issues with this. Thank you again!
