### ISSUE TITLE
handler.go , getURL headers Param not use

### ISSUE THREAD

**Issue by ollylu** [Comcast/trickster#151]
handler.go , getURL function ,headers Param not use
resp, err := client.Do(&http.Request{Method: method, URL: parsedURL})

**Comment by jranson** [comment]
Thanks for this report! With the 1.0 (`next`) branch, the Headers have been re-worked and are fully passed through up to the origin, and response headers back down to the client. Hopefully that will address this issue and we can close it once we merge `next` into `master`.  It should be in the next several weeks. Let us know if that is ok! Thank you again. JR
