### ISSUE TITLE
Please support Redis Cluster.

### ISSUE THREAD

**Issue by thinker0** [Comcast/trickster#157]

**Comment by jranson** [comment]
@thinker0 This looks fairly easy to do, the go-redis package we are already using for Redis supports Redis Cluster as well. I will take a look and try to have Redis Cluster support ready for the 1.0 Beta Release that is coming in a few days.

**Comment by thinker0** [comment]
Thanks ^________^;

2019년 3월 28일 (목) 오후 12:42, James Ranson <notifications@github.com>님이 작성:
