### ISSUE TITLE
Empty query results return null instead of empty array

### ISSUE THREAD

**Issue by jidr** [Comcast/trickster#20]
In Grafana (4+ I believe, but it might be 5 series only), if you run a query that returns no datapoints from trickster, it will probably fail to render with a `Cannot read property length of: null` error.

If you run the same query through prometheus it will return `[]` instead of `null`, which is what grafana expects. I believe that it's a matter of an initialised variable, however I don't know enough Go to submit a pull request, sorry!
Trickster does look promising though, great stuff.

Relevant:
https://danott.co/posts/json-marshalling-empty-slices-to-empty-arrays-in-go.html

Example data:
trickster:
```
{
status: "",
  data: {
    resultType: "",
    result: null
  }
}
```

prometheus:
```
{
status: "success",
  data: {
    resultType: "matrix",
    result: []
  }
}
```

update: had pasted wrong response from trickster, this is correct

**Comment by jranson** [comment]
@jidr Thanks! I've identified the root cause and will take a stab at fixing this evening.

**Comment by jranson** [comment]
@jidr Release v0.0.11 should address this. Thank you again!

**Comment by jidr** [comment]
Checked out the fix and it certainly did address the issue. I have trickster deployed now and wow, what a difference it makes for grafana.
