### ISSUE TITLE
Retry Logic for caches

### ISSUE THREAD

**Issue by dheerajkulakarni** [Comcast/trickster#219]
We use aws redis for caching , Due to some reasons the connection for redis is getting lost and immediately trickster gets down  ,it would be  great if there is an option like no of retries it can try before an exception is thrown 

Exception Thrown

> goroutine 11 [running]:
main.(*RedisCache).ReapOnce(0xc000113340)
	/go/src/github.com/Comcast/trickster/redis.go:84 +0x6e7
main.(*RedisCache).Reap(0xc000113340)
	/go/src/github.com/Comcast/trickster/redis.go:61 +0x2b
created by main.(*RedisCache).Connect
	/go/src/github.com/Comcast/trickster/redis.go:42 +0x241

**Comment by jranson** [comment]
@dheerajkulakarni Thanks for the report. In PR #220, we have exposed _all_ go-redis options to the Trickster configuration, which gives you 12 new knobs for tuning the redis client - including command retries.  When this PR is merged and we cut a new 1.0 beta release, you'll be able to test out the features. I see from your log output that you are using 0.1.x and we will not be adding these new tuning features into that codebase.

**Comment by dheerajkulakarni** [comment]
@jranson  hey thank you so much , it would be so helpful for us .
