### ISSUE TITLE
Panic on v1.0.7-beta7

### ISSUE THREAD

**Issue by sylr** [Comcast/trickster#237]
```
2019/06/13 14:34:25 http: panic serving 10.199.147.163:38494: runtime error: index out of range
goroutine 1341361 [running]:
net/http.(*conn).serve.func1(0xc004122000)
        /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x9e5ec0, 0xfe8550)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/Comcast/trickster/internal/proxy/origins/prometheus.(*MatrixEnvelope).Crop(0xc0005c41e0, 0x0, 0xed4942ab8, 0xff9840, 0x0, 0xed49454e8, 0xff9840)
        /go/src/github.com/Comcast/trickster/internal/proxy/origins/prometheus/matrix.go:141 +0xae3
github.com/Comcast/trickster/internal/proxy/engines.DeltaProxyCacheRequest(0xc0089b8b00, 0xb730c0, 0xc003c2a000, 0xb7e560, 0xc0001569b0, 0xb7a980, 0xc000156910, 0x13a52453c000)
        /go/src/github.com/Comcast/trickster/internal/proxy/engines/deltaproxycache.go:236 +0xf14
github.com/Comcast/trickster/internal/proxy/origins/prometheus.(*Client).QueryRangeHandler(0xc0001569b0, 0xb730c0, 0xc003c2a000, 0xc001738300)
        /go/src/github.com/Comcast/trickster/internal/proxy/origins/prometheus/handler_query_range.go:26 +0x2d7
net/http.HandlerFunc.ServeHTTP(0xc000240040, 0xb730c0, 0xc003c2a000, 0xc001738300)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000168180, 0xb730c0, 0xc003c2a000, 0xc001738100)
        /go/pkg/mod/github.com/gorilla/mux@v1.7.1/mux.go:212 +0xe3
github.com/gorilla/handlers.CompressHandlerLevel.func1(0xb73700, 0xc0001b41c0, 0xc001738100)
        /go/pkg/mod/github.com/gorilla/handlers@v1.4.0/compress.go:146 +0x1aa
net/http.HandlerFunc.ServeHTTP(0xc000244540, 0xb73700, 0xc0001b41c0, 0xc001738100)
        /usr/local/go/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc000140ea0, 0xb73700, 0xc0001b41c0, 0xc001738100)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc004122000, 0xb75040, 0xc008ad8000)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by sylr** [comment]
I don't know if it's related but I'm using a version of prometheus with the xrate patch of @free

https://github.com/sylr/prometheus/commit/9d315c4e770e8c501af6f6ffa3274d0e37506f2d

**Comment by jtorkkel** [comment]
We are using standard 2.8.x Prometheus and I can see same panic as in beta-6 but in different use cases in Beta7. I saw issues when I was modifying queries, I suspect that error in query like two ,, between labels trigger the issue or timeout in query.

**Comment by jranson** [comment]
I've been able to identify at least one root cause for the panic, have added a test to catch it and am working on the patch. The condition I found is when one or more of the the query's resulting metrics stops having new data (e.g., some errors you are charting that have since been mitigated) for a long enough time that all of the metric's timestamps are old enough to purge. The panic occurs during that Crop() call when the resulting metric's value set is completely empty, but other metrics in the result set still have values.

**Comment by jranson** [comment]
I have switched out some of the cropping mechanics to use a pattern i totally script kiddied from https://play.golang.org/p/346LnF-E2H0 (credit the 2018 update part of https://vbauerster.github.io/2017/04/removing-items-from-a-slice-while-iterating-in-go/), and it seems to pass all of the unit tests I could come up with for the various cropping scenarios. We will cut beta 8 on Monday with this fix. I really appreciate all of the community support for the beta program, and for sticking with us through the various releases and their hiccups. You all are helping to make Trickster better, so thanks very much!
