### ISSUE TITLE
No histogram for cache hit, cache_status="" for unknown cache (rmiss) type and trickster_proxy_requests_total duplicate to trickster_proxy_request_duration_seconds_count

### ISSUE THREAD

**Issue by jtorkkel** [Comcast/trickster#243]
1. Cache hit does not expose histogram, would be useful to see how fast response from hit are queried. Some large hit might take long time.
2. It is unnecessary to have separate total counter because histogram expose also _count. Only histogram should be used
3. cache_status="" reported in metrics, maybe it should be "rmiss"

### debug log for complex query "hit" taking ~1.5 second based on logs. Response had 300x981 sample
time=2019-06-20T13:11:47.752259273Z app=trickster caller=cache/filesystem/filesystem.go:118 level=debug event="filesystem cache retrieve" key=10.53.16.101:19090.0a8a4881669a0668cb6a82944582b1e6.sz dataFile=/tmp/trickster/10.53.16.101:19090.0a8a4881669a0668cb6a82944582b1e6.sz.data
time=2019-06-20T13:11:47.75236384Z app=trickster caller=proxy/engines/cache.go:50 level=debug event="decompressing cached data" cacheKey=10.53.16.101:19090.0a8a4881669a0668cb6a82944582b1e6.sz
time=2019-06-20T13:11:49.197774508Z app=trickster caller=proxy/engines/deltaproxycache.go:293 level=debug event="delta routine completed" cacheKey=10.53.16.101:19090.0a8a4881669a0668cb6a82944582b1e6 cacheStatus=hit reqStart=2019-06-18T21:00:00Z reqEnd=2019-06-19T21:00:00Z

### Example metrics
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query",status="kmiss",le="0.05"} 45
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query",status="kmiss",le="+Inf"} 52
trickster_proxy_request_duration_seconds_sum{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query",status="kmiss"} 2.9979508339999996
trickster_proxy_request_duration_seconds_count{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query",status="kmiss"} 52
trickster_proxy_requests_total{cache_status="kmiss",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query"} 52

trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="",le="0.05"} 4
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="",le="+Inf"} 18
trickster_proxy_request_duration_seconds_sum{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status=""} 11.562895791999999
trickster_proxy_request_duration_seconds_count{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status=""} 18
trickster_proxy_requests_total{cache_status="",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range"} 18

trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="kmiss",le="0.05"} 1019
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="kmiss",le="+Inf"} 1500
trickster_proxy_request_duration_seconds_sum{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="kmiss"} 456.886482596
trickster_proxy_request_duration_seconds_count{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="kmiss"} 1500
trickster_proxy_requests_total{cache_status="kmiss",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range"} 1500

trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="phit",le="0.1"} 13
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="phit",le="+Inf"} 258
trickster_proxy_request_duration_seconds_sum{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="phit"} 902.5842434989999
trickster_proxy_request_duration_seconds_count{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range",status="phit"} 258
trickster_proxy_requests_total{cache_status="phit",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range"} 258

trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/series",status="kmiss",le="0.05"} 36
trickster_proxy_request_duration_seconds_bucket{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/series",status="kmiss",le="+Inf"} 237
trickster_proxy_request_duration_seconds_sum{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/series",status="kmiss"} 272.1581791400001
trickster_proxy_request_duration_seconds_count{http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/series",status="kmiss"} 237
trickster_proxy_requests_total{cache_status="kmiss",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/series"} 237

### No histogram for hit
trickster_proxy_requests_total{cache_status="hit",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query"} 39
trickster_proxy_requests_total{cache_status="hit",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/query_range"} 3222
trickster_proxy_requests_total{cache_status="hit",http_status="200",method="GET",origin_name="default",origin_type="prometheus",path="/api/v1/series"} 220

**Comment by jranson** [comment]
@jtorkkel Thanks for this feedback, I will add \#1 and take a look at \#3. If @SuperQ agrees with #2, I am happy to take it out and avoid redundancy :)

**Comment by jranson** [comment]
@jtorkkel for # 3 (cache_status=""), this label accounts for proxy-only requests and so there actually is no cache status. As you accurately implied, this includes time series requests with time ranges that fully predate oldest cacheable timestamp for the query, since they are punted to the proxy. (But that is different from actual range misses, where there is data for the query in the cache, but none for the requested time range), but also includes requests to `/api/v1/labels` and other paths that are simply not known by Trickster to be cacheable. You can simply exclude them in your prometheus query (e.g., `sum(delta(trickster_proxy_requests_total{cache_status =~"hit|phit|kmiss|rmiss"}[1m])) by (cache_status)`). We can also populate this with a string like "none", but like # 2, I will defer to @SuperQ for expert guidance.

**Comment by jranson** [comment]
@jtorkkel Beta 9 includes this feature request, see the release notes for details. Please let us know how this works out for you. Thanks!

**Comment by SuperQ** [comment]
For metrics like cache hits/misses, we usually suggest having spearate total counters like `misses_total` and `requests_total`. This allows for easy things like `requests_total - misses_total` or `misses_total / requests_total`.

**Comment by jtorkkel** [comment]
I would like to see non empty cache_status like ”none”. Would help in dashboard creation because empty label would not be visible.

I tried to validate added histogram/bucket for “hit” in “lru” mode. Seems that only
path=“/api/v1/query_range” is counted but not path=“/api/v1/query” or path=“/api/v1/series” are not. They were counted in “_total”.

**Comment by jranson** [comment]
These changes are all fully released in beta10. Thank you for the report!
