### ISSUE TITLE
1.0.9-beta9 inconsistently/incorrectly tagged

### ISSUE THREAD

**Issue by yosifkit** [Comcast/trickster#256]
It is currently tagged as `1.09-beta9` where the attached assets are named for `1.0.9` and previous releases all use three part version number with optional pre-release qualifier.

https://github.com/Comcast/trickster/tags

**Comment by sylr** [comment]
Yes, @jranson, please be consisten.

Also, please respect the SemVer spec and do not increment patch version level for beta versions.

Please see: https://semver.org/#spec-item-9

**Comment by jranson** [comment]
@sylr @yosifkit thank you for this report, with the latest release we have adopted 1.0.0 as the semantic version per your feedback.
