### ISSUE TITLE
helm chart's `readme` and `values.yaml` correction

### ISSUE THREAD

**Issue by infa-ddeore** [Comcast/trickster#257]
values.yaml and README.md: `image.tag` needs to be `0.1.10` since `0.1.7` tag doesn't exist

README.md: `persistentVolume.enabled` is `false` by default but README has it as `true`

**Comment by jranson** [comment]
@infa-ddeore I am away on holiday with very little net access, but we will review this issue next week when I am back. Thank you for the report!

**Comment by jranson** [comment]
Hi @infa-ddeore - we have finally been able to circle back and get the helm items cleaned up. We've removed the values table from the README and now refer users to the values.yaml file, which is exhaustively documented inline. We've also fixed up the image.tag to be correct and working. Thanks for this report, and sorry the issue has lingered for several months.
