### ISSUE TITLE
Sharing the cache across user sessions?

### ISSUE THREAD

**Issue by sandyteenan** [Comcast/trickster#258]
We're testing for the sharing of the cache across different user browser sessions - we see that if I run a grafana query there is an improvement the second time onwards, but if I pass that same url to a colleague, they get same results - slow on the first execution, faster on the second execution onwards.

Tested on 0.1.7, 0.1.10 and 1.0.9. Memory cache. Running with multiple origins.

Can / should cache results be shared across different browser sessions?

**Comment by sandyteenan** [comment]
`[main]
# instance_id allows you to run multiple trickster processes on the same host and log to separate files
# Useful for baremetal, not so much for elastic deployments, so only uncomment if you really need it
# default is 0, which means ignored
#instance_id = 0

# Configuration options for the Proxy Server
[proxy_server]
# listen_port defines the port on which Trickster's Proxy server listens.
# The default proxy is for Prometheus, so we use 9090 by default, just like Prometheus does
listen_port = 9090
# listen_address defines the ip on which Trickster's Proxy server listens.
# empty by default, listening on all interfaces
# listen_address = ''

[caches]

    [caches.default]
    # cache_type defines what kind of cache Trickster uses
    # options are 'bbolt', 'badger', 'filesystem', 'memory', and 'redis'
    # The default is 'memory'.
    type = 'memory'

    # compression determines whether the cache should be compressed. default is true
    # changing the compression setting will leave orphans in your cache for the duration of timeseries_ttl_secs
    compression = true

    # timeseries_ttl_secs defines the relative expiration of cached timeseries. default is 6 hours (21600 seconds)
    timeseries_ttl_secs = 21600

    # fastforward_ttl_secs defines the relative expiration of cached fast forward data. default is 15s
    fastforward_ttl_secs = 15

    # object_ttl_secs defines the relative expiration of generically cached (non-timeseries) objects. default is 30s
    object_ttl_secs = 300

        ### Configuration options for the Cache Index
        # The Cache Index handles key management and retention for bbolt, filesystem and memory
        # Redis and BadgerDB handle those functions natively and does not use the Trickster's Cache Index
        [caches.default.index]

        # reap_interval_secs defines how long the Cache Index reaper sleeps between reap cycles. Default is 3 (3s)
        reap_interval_secs = 3

        # flush_interval_secs sets how often the Cache Index saves its metadata to the cache from application memory. Default is 5 (5s)
        flush_interval_secs = 5

        # max_size_bytes indicates how large the cache can grow in bytes before the Index evicts least-recently-accessed items. default is 512MB
        max_size_bytes = 536870912

        # max_size_backoff_bytes indicates how far below max_size_bytes the cache size must be to complete a byte-size-based eviction exercise. default is 16MB
        max_size_backoff_bytes = 16777216

        # max_size_objects indicates how large the cache can grow in objects before the Index evicts least-recently-accessed items. default is 0 (infinite)
        max_size_objects = 0

        # max_size_backoff_objects indicates how far under max_size_objects the cache size must be to complete object-size-based eviction exercise. default is 100
        max_size_backoff_objects = 100

        ### Configuration options when using a Redis Cache
        [caches.default.redis]

        # client_type indicates which kind of Redis client to use. Options are: 'standard', 'cluster' and 'sentinel'
        # default is 'standard'
        client_type = 'standard'

        # Supported by Redis (standard)
        # These configurations are ignored by Redis Sentinel and Redis Cluster
        # protocol defines the protocol for connecting to redis ('unix' or 'tcp') 'tcp' is default
        protocol = 'tcp'
        # endpoint defines the fqdn+port or path to a unix socket file for connecting to redis
        # default is 'redis:6379'
        endpoint = 'redis:6379'
        #

        # Supported by Redis Cluster and Redis Sentinel
        # These conigurations are ignored by Redis (standard)
        # endpoints is used for Redis Cluster and Redis Sentinel to define a list of endpoints
        # default is ['redis:6379']
        endpoints = ['redis:6379']
        #

        # Supported by Redis Sentinel
        # These conigurations are ignored by Redis (standard) and Redis Cluster
        # sentinel_master should be set when using Redis Sentinel to indicate the Master Node
        sentinel_master = ''
        #

        # password provides the redis password
        # default is empty
        password = ''

        # These options are supported by all Redis Client Types
        # See the go-redis documentation at https://github.com/go-redis/redis/blob/master/options.go 
        # for more information on tuning these settings

        # db is the Database to be selected after connecting to the server. default is 0
        # db = 0

        # max_retries is the maximum number of retries before giving up on the command
        # max_retries = 0

        # min_retry_backoff_ms is the minimum backoff time between each retry
        # min_retry_backoff_ms = 8

        # max_retry_backoff_ms is the maximum backoff time between each retry
        # max_retry_backoff_ms = 512

        # dial_timeout_ms is the timeout for establishing new connections
        # dial_timeout_ms = 5000

        # read_timeout_ms is the timeout for socket reads. If reached, commands will fail with a timeout instead of blocking.
        # read_timeout_ms = 3000

        # write_timeout_ms is the timeout for socket writes. If reached, commands will fail with a timeout instead of blocking.
        # write_timeout_ms = 3000

        # pool_size is the maximum number of socket connections.
        # pool_size = 20

        # min_idle_conns is the minimum number of idle connections which is useful when establishing new connection is slow.
        # min_idle_conns = 0

        # max_conn_age_ms is the connection age at which client retires (closes) the connection.
        # max_conn_age_ms = 0

        # pool_timeout_ms is the amount of time client waits for connection if all connections are busy before returning an error.
        # pool_timeout_ms = 4000

        # idle_timeout_ms is the amount of time after which client closes idle connections.
        # idle_timeout_ms = 300000

        # idle_check_frequency_ms is the frequency of idle checks made by idle connections reaper.
        # idle_check_frequency_ms = 60000


        ### Configuration options when using a Filesystem Cache
        [caches.default.filesystem]
        # cache_path defines the directory location under which the Trickster cache will be maintained
        # default is '/tmp/trickster'
        cache_path = '/tmp/trickster'

        # Configuration options when using a bbolt Cache
        [caches.default.bbolt]

        # filename defines the file where the Trickster cache will be maintained
        # default is 'trickster.db'
        filename = 'trickster.db'

        # bucket defines the name of the BotlDb bucket (similar to a namespace) under which our key value store lives
        # default is 'trickster'
        bucket = 'trickster'

        # Configuration options when using a Badger cache
        [caches.default.badger]
        # directory defines the directory location under which the Badger data will be maintained
        # default is '/tmp/trickster'
        directory = '/tmp/trickster'
        # directory defines the directory location under which the Badger value log will be maintained
        # default is '/tmp/trickster'
        value_directory = '/tmp/trickster'

    # Example of a second cache, sans comments, that origin configs below could use with: cache_name = 'bbolt_example'
    #
    # [caches.bbolt_example]
    # type = 'bbolt'
    # compression = true
    # timeseries_ttl_secs = 21600
    # fastforward_ttl_secs = 15
    # object_ttl_secs = 30

        # [caches.bbolt_example.bbolt]
        # filename = 'trickster.db'
        # bucket = 'trickster'

        # [caches.bbolt_example.index]
        # reap_interval_secs = 3
        # flush_interval_secs = 5
        # max_size_bytes = 536870912
        # size_backoff_bytes = 16777216

# Configuration options for mapping Origin(s)
[origins]

    # example origin named default. default is always created with these settings unless a different origin is defined here.
    [origins.default]

    # is_default describes whether this origin is the default origin considered when routing http requests
    # it is false, by default; but if you only have a single origin configured, is_default will be true unless explicitly set to false
    is_default = true

    # type identifies the origin type. Valid options are 'prometheus', 'influxdb', 'irondb'
    # default is prometheus.
    type = 'prometheus'

    # cache_name identifies the name of the cache (configured above) that you want to use with this origin proxy.
    cache_name = 'default'

    # scheme identifies the scheme
    # default is http
    scheme = 'http'

    # host identifies the upstream origin by fqdn/IP and port
    # default is prometheus:9090
    host = 'apps-01.example.com'

    # path_prefix provides any path that is prefixed onto the front of the client's requested path
    # default is empty
    path_prefix = ''

    # timeout_secs defines how many seconds Trickster will wait before aborting and upstream http request. Default: 180s
    # timeout_secs = 180

    # keep_alive_timeout_secs defines how long Trickster will wait before closing a keep-alive connection due to inactivity
    # if the origin's keep-alive timeout is shorter than Trickster's, the connect will be closed sooner. Default: 300
    # keep_alive_timeout_secs = 300

    # max_idle_conns set the maximum concurrent keep-alive connections Trickster may have opened to this origin
    # additional requests will be queued. Default: 20
    # max_idle_conns = 20

    # api_path defines the path of the Upstream Origin's API (usually '/api/v1')
    api_path = '/api/v1'

    # ignore_no_cache_header disables a client's ability to send a no-cache to refresh a cached query. Default is false
    # ignore_no_cache_header = false

    # timeseries_retention_factor defines the maximum number of recent timestamps to cache for a given query. Default is 1024
    # timeseries_retention_factor = 1024

    # timeseries_eviction_method selects the metholodogy used to determine which timestamps are removed once
    # the timeseries_retention_factor limit is reached. options are 'oldest' and 'lru'. Default is 'oldest'
    # timeseries_eviction_method = 'oldest'

    # fast_forward_disable, when set to true, will turn off the 'fast forward' feature for any requests proxied to this origin
    # fast_forward_disable = false

    # backfill_tolerance_secs prevents new datapoints that fall within the tolerance window (relative to time.Now) from being cached
    # Think of it as "never cache the newest N seconds of real-time data, because it may be preliminary and subject to updates"
    # default is 0
    # backfill_tolerance_secs = 0

    # For multi-origin support, origins are named, and the name is the second word of the configuration section name.
    # In this example, an origin is named "foo".
    # Clients can indicate this origin in their path (http://trickster.example.com:9090/foo/api/v1/query_range? .....)
    # there are other ways for clients to indicate which origin to use in a multi-origin setup. See the documentation for more information

    [origins.apps01]
    is_default = false
    type = 'prometheus'
    cache_name = 'default'
    scheme = 'http'
    host = 'apps-01.example.com'
    path_prefix = ''
    api_path = '/api/v1'
    ignore_no_cache_header = false
    timeseries_retention_factor = 1024
    timeseries_eviction_method = 'oldest'
    timeout_secs = 180
    backfill_tolerance_secs = 180
    [origins.messages01]
    is_default = false
    type = 'prometheus'
    cache_name = 'default'
    scheme = 'http'
    host = 'messages-01.example.com'
    path_prefix = ''
    api_path = '/api/v1'
    ignore_no_cache_header = false
    timeseries_retention_factor = 1024
    timeseries_eviction_method = 'oldest'
    timeout_secs = 180
    backfill_tolerance_secs = 180

# Configuration Options for Metrics Instrumentation
[metrics]
# listen_port defines the port that Trickster's metrics server listens on at /metrics
listen_port = 8082
# listen_address defines the ip that Trickster's metrics server listens on at /metrics
# empty by default, listening on all interfaces
# listen_address = ''

# Configuration Options for Logging Instrumentation
[logging]
# log_level defines the verbosity of the logger. Possible values are 'debug', 'info', 'warn', 'error'
# default is info
log_level = 'debug'

# log_file defines the file location to store logs. These will be auto-rolled and maintained for you.
# not specifying a log_file (this is the default behavior) will print logs to STDOUT
# log_file = '/some/path/to/trickster.log'`

**Comment by jranson** [comment]
@sandyteenan yes, the cache is shared across browser sessions. The first load can be slow for several reasons. For example, the other user may need to download or revalidate all the other pieces of (assuming) the Grafana application itself - javascript, css, etc. Separately, Trickster uses a unique cache record per `step` parameter on the Prometheus query. This way, we don't have to iterate the cache record to extract the data points that are specific to the step the user has requested; instead we just have to open the cache record, trim the edges and then serve it, which ensures the most optimal render times. One of the unique things about Grafana is that it adjusts the step value on upstream prometheus queries based on your screen resolution, browser window width, and browser zoom level. The easiest way for you to verify the cache is shared across users (with the same step) is to run a couple of browsers locally (Chrome, Firefox, Safari) on your computer, ensuring that each window is sized identically and at 100% zoom, and then open your main Grafana URL to load it's artifacts, then load same dashboard URL in each browser to observe the immediate acceleration following the load in the first browser. You can even use a Chrome regular window and a Chrome incognito window to test this.

**Comment by jranson** [comment]
btw, another condition we have encountered on slow first loads is when you have a very large number of `/api/v1/series` requests to populate dashboard $variable values. These are unfortunately not cacheable and can cause the initial loads for each user to be a bit slow, while the subsequent timeseries refreshes are very fast. You can check for this on your local browser by turning on browser the developer tools and observing which individual http requests are slow on the first load versus subsequent in-dashboard refreshes. If your series requests are slow, that would be the reason and is unrelated to the cache differentiation by `step`.

**Comment by sandyteenan** [comment]
Thanks for the clarification @jranson! I've already tuned the variable population queries, which becomes even more important now I know they're not cacheable.

The `step` logic makes sense, so I'll verify the conditions across user sessions and it's something we'll need to be aware of.

Thanks again for the quick responses!

**Comment by jranson** [comment]
@sandyteenan just wanted to check and see if this issue is satisfactorily resolved for you. We'll close the issue next week if there is no more activity. Thanks for trying Trickster and giving us great feedback. Hope it's still working well for you!

**Comment by sandyteenan** [comment]
Yes, I'm very happy with how it's working thanks @jranson !
