### ISSUE TITLE
Include Vendor libraries in Repo

### ISSUE THREAD

**Issue by LimitlessEarth** [Comcast/trickster#260]
The vendored dependancies should be included in the github repo.

This will have a couple of quality of life improvements:
- Faster CI - no redownloading on every run
- Faster Docker build - no redownloading on every build in the 2-step Dockerfile
- etc.

Most of the projects I have worked on do it and I have not had issue. Prometheus does it as well.
https://github.com/prometheus/prometheus/tree/master/vendor

**Comment by jranson** [comment]
If there are no objections from the community,  I am fine with this. Is this just a matter of removing `vendor` from `.gitignore` and `git add`'ing?

**Comment by jacksontj** [comment]
@jranson yes, thats it :)

Also as an added benefit you avoid any possibility of an upstream tag/branch change breaking your builds -- which is nice (I have had that issue happen a couple of times before).

**Comment by jranson** [comment]
Merged #269 to `next`
