### ISSUE TITLE
trickster does not suport /api/v1/series on multi-origin

### ISSUE THREAD

**Issue by roidelapluie** [Comcast/trickster#27]
Apr 09 16:43:34 grafana01 trickster[18199]: 2018/04/09 16:43:34 http: panic serving 127.0.0.1:34936: runtime error: invalid memory address
or nil pointer dereference
Apr 09 16:43:34 grafana01 trickster[18199]: goroutine 4078 [running]:                                             
Apr 09 16:43:34 grafana01 trickster[18199]: net/http.(*conn).serve.func1(0xc425de3040)                                                     
Apr 09 16:43:34 grafana01 trickster[18199]: /usr/local/go/src/net/http/server.go:1697 +0xd0                       
Apr 09 16:43:34 grafana01 trickster[18199]: panic(0x777940, 0xa08940)                                                                      
Apr 09 16:43:34 grafana01 trickster[18199]: /usr/local/go/src/runtime/panic.go:491 +0x283                        
Apr 09 16:43:34 grafana01 trickster[18199]: main.(*TricksterHandler).promFullProxyHandler(0xc420054780, 0x9dcc00, 0xc428f8f950, 0xc434c8170
0)                                                                                                                
Apr 09 16:43:34 grafana01 trickster[18199]: /repository/workspace/modules/com.github.comcast.trickster/master/release/src/github.com/comcas
t/trickster/handlers.go:74 +0x3f7                                                                                 
Apr 09 16:43:34 grafana01 trickster[18199]: main.(*TricksterHandler).(main.promFullProxyHandler)-fm(0x9dcc00, 0xc428f8f950, 0xc434c81700)  
Apr 09 16:43:34 grafana01 trickster[18199]: /repository/workspace/modules/com.github.comcast.trickster/master/release/src/github.com/comcas
t/trickster/main.go:67 +0x48                                                                                                               
Apr 09 16:43:34 grafana01 trickster[18199]: net/http.HandlerFunc.ServeHTTP(0xc42011a710, 0x9dcc00, 0xc428f8f950, 0xc434c81700)
Apr 09 16:43:34 grafana01 trickster[18199]: /usr/local/go/src/net/http/server.go:1918 +0x44                                                
Apr 09 16:43:34 grafana01 trickster[18199]: github.com/comcast/trickster/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200f96c0, 0x
9dcc00, 0xc428f8f950, 0xc434c81700)                                                                                                        
Apr 09 16:43:34 grafana01 trickster[18199]: /repository/workspace/modules/com.github.comcast.trickster/master/release/src/github.com/comcas
t/trickster/vendor/github.com/gorilla/mux/mux.go:159 +0xed                                                                                 
Apr 09 16:43:34 grafana01 trickster[18199]: github.com/comcast/trickster/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1(0x9d
d140, 0xc4249fd960, 0xc423592100)
Apr 09 16:43:34 grafana01 trickster[18199]: /repository/workspace/modules/com.github.comcast.trickster/master/release/src/github.com/comcas
t/trickster/vendor/github.com/gorilla/handlers/compress.go:146 +0x462
Apr 09 16:43:34 grafana01 trickster[18199]: net/http.HandlerFunc.ServeHTTP(0xc42011c920, 0x9dd140, 0xc4249fd960, 0xc423592100)
Apr 09 16:43:34 grafana01 trickster[18199]: /usr/local/go/src/net/http/server.go:1918 +0x44
Apr 09 16:43:34 grafana01 trickster[18199]: net/http.serverHandler.ServeHTTP(0xc420073860, 0x9dd140, 0xc4249fd960, 0xc423592100)
Apr 09 16:43:34 grafana01 trickster[18199]: /usr/local/go/src/net/http/server.go:2619 +0xb4
Apr 09 16:43:34 grafana01 trickster[18199]: net/http.(*conn).serve(0xc425de3040, 0x9dd980, 0xc422cfdec0)
Apr 09 16:43:34 grafana01 trickster[18199]: /usr/local/go/src/net/http/server.go:1801 +0x71d
Apr 09 16:43:34 grafana01 trickster[18199]: created by net/http.(*Server).Serve
Apr 09 16:43:34 grafana01 trickster[18199]: /usr/local/go/src/net/http/server.go:2720 +0x288

**Comment by roidelapluie** [comment]
Note: cache_type = 'filesystem'

**Comment by roidelapluie** [comment]
Jest before: time=2018-04-09T14:43:34.491787239Z app=trickster caller=trickster/handlers.go:225 level=error
event="error downloading url" url="http://prometheus:9090//mycarenet2/api/v1/series?end=1523284955&match%5B%5D=ifHCOutOctets&start=1523277755" detail="Get http://prometheus:9090/foo2/api/v1/series?end=1523284955&match%5B%5D=ifHCOutOctets&start=1523277755: dial tcp 155.45.169.233:9090: i/o timeout"

**Comment by roidelapluie** [comment]
Looks like origin_url = 'http://10.19.2.37:9090' is ignored in my config

**Comment by crandles** [comment]
Can you share your config?

**Comment by jranson** [comment]
@roidelapluie  The panic appears to be a bug we will take a look at (i'll re-update the issue topic), but your overall situation (not picking up your configured origins) looks to be an issue with how you are configuring multi-origin in Trickster and in Grafana. Short answer: user error. You did not configure a default origin ([origins.default]), so when you do not provide a host-header-based, path-based or parameter-based origin moniker in your Grafana config, Trickster will choose the default origin of `http://prometheus:9090`. You should be able to update your Grafana Data Sources configs by appending `foo1` or `foo2` to the paths (e.g., `http://<your_trickster_endpoint:9090/foo1`) as described in [https://github.com/Comcast/trickster/blob/master/docs/multi-origin.md]. The "path-based" section (complete with a screen shot of how to configure Grafana) should point you in the right direction.

**Comment by roidelapluie** [comment]
@jranson  The error is that we do not proxy /api/v1/series when useng path based multi origin. The panic is because we ignore proxy errors.

**Comment by jranson** [comment]
Ah, so this is specific to /series (but not /query and /query_range)?  Very interesting! Will take a look today!

**Comment by jranson** [comment]
@roidelapluie I've found the root cause and will issue a fix shortly.
