### ISSUE TITLE
update makefile to bake build time, commit id, etc., into binary

### ISSUE THREAD

**Issue by jranson** [Comcast/trickster#283]
as the release manager for trickster, i would like to have the trickster binary's build time and commit id baked into the binary when i run `make build`

**Comment by pavan-kalyan** [comment]
by baking the build time and commit ID into the binary, do you mean using ldflags to assign the respective variables in main.go from the makefile (as suggested here https://stackoverflow.com/questions/11354518/application-auto-build-versioning) ?

**Comment by pavan-kalyan** [comment]
I would like to work on this issue, if that's okay ?

**Comment by jranson** [comment]
@pavan-kalyan I have assigned the issue to you, thanks! Note that you'll want to base your changes off of the `next` branch and PR against that. I do not have a preferred implementation, so long as it is done similarly to how other projects in this space also do it (e.g., Prometheus).  Thanks again for contributing and participating in Hacktoberfest!

**Comment by jranson** [comment]
@pavan-kalyan it looks like someone might have beaten you to this one (see PR #292), sorry about that. If you would like to provide a review to that PR, that would help me out a lot, and you'll get contributor credit.

**Comment by pavan-kalyan** [comment]
Thanks for the opportunity, i have reviewed.

**Comment by jranson** [comment]
Implemented in #295; Thanks @pavan-kalyan!
