### ISSUE TITLE
make better use of consts and iota enumerations 

### ISSUE THREAD

**Issue by jranson** [Comcast/trickster#289]
Lots of places in the codebase still pass around and compare strings, some number-based iota enumerations would be more ideal. We've started some work on this in `next` (see [TimeseriesEvictionMethod](https://github.com/Comcast/trickster/blob/next/internal/config/timeseries_eviction_method.go)) and in pr #280, but could use some help going through the `next` codebase and cleaning up these issues and anything else that does not align with best practices. We'd really appreciate the help!

**Comment by Flamingo09** [comment]
Hey @jranson , can you assign me this issue.

**Comment by jranson** [comment]
All set! Thanks for your help!

**Comment by jranson** [comment]
we have this mostly cleaned up in `next` at this point. still some minor nits but things are largely in a good place with this, so closing
