### ISSUE TITLE
1.0 documentation review

### ISSUE THREAD

**Issue by jranson** [Comcast/trickster#290]
As we are ramping up for the 1.0 release, which includes numerous changes and updates, the documentation may be out of date in some areas and missing descriptions of new features in others. The assignee for this issue would compare all of the comments and values in the [example config file](https://github.com/Comcast/trickster/blob/next/cmd/trickster/conf/example.conf) in `next` with the [various documentation](https://github.com/Comcast/trickster/tree/next/docs) in `next`, and outline what is missing or outdated. As the ticket says, this is just a review, and not necessarily an implementation, so we are really looking to get a starting point on closing the gaps by knowing what they are, but appreciate any help with making corrections and additions to improve the documentation for 1.0 as well. We welcome all help!

**Comment by arsh-7** [comment]
Hi @jranson i would like to help with documentation for 1.0

**Comment by jranson** [comment]
Sounds great, thank you! Please hit me up with any questions.

**Comment by jranson** [comment]
Docs are all cleaned up in `next`
