### ISSUE TITLE
Support output format for Remote Storage Adapter (Prometheus)

### ISSUE THREAD

**Issue by jranson** [Comcast/trickster#3]
Implement the Prometheus `remote_read` API, so that trickster may serve as a remote_read endpoint. 

This will allow trickster to act as a remote_read endpoint for a Prometheus instance, so that all queries going through Prometheus will use trickster as a cache, including any defined alerts.

https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage/remote_storage_adapter

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cremote_read%3E

**Comment by davidquarles** [comment]
@jranson Any idea just how involved this might be?  I'm not super familiar with this codebase today.  We just attempted to run trickster as a sidecar between prometheus and `thanos sidecar` and hit a wall here.  We could potentially help, if that's useful.

**Comment by jranson** [comment]
I am not quite sure, I do not have any experience w/ this, it was a feature request we moved over from the internal repo @ Comcast that someone had requested. CC: @crandles

**Comment by SuperQ** [comment]
I don't see how this fits into Trickster. The remote read interface is designed so that one Prometheus server can read raw data and process it with PromQL. Trickster is a proxy, not a backing storage service.

**Comment by BertHartm** [comment]
I have a need for this for rule evaluation. I use remote read to have prometheus evaluate rules from data in backing storage. if trickster could cache remote read protocol it could dramatically help my rule evaluation queries.

@SuperQ / @jranson thoughts on reopening for that use case?
