### ISSUE TITLE
Trickster on helm hub

### ISSUE THREAD

**Issue by ghost** [Comcast/trickster#317]
Hi,

Do you think if it's possible to publish the helm manifests to [helm hub](https://hub.helm.sh/) ?
It would be awesome to facilitate the integration in kubernetes environment.

**Comment by jranson** [comment]
@damienhb That's a great idea. We are almost ready to feature lock the upcoming 1.0 release (which will mean no more breaking configmap changes, etc). As soon as we have that piece in place, we'll get the finalized 1.0 helm chart published over on helm hub. I will follow up on this ticket once we're all ready.

**Comment by Dudesons** [comment]
@jranson thank you for the information there is a way to keep in touch of  the GA of the 1.0 release ?

**Comment by jranson** [comment]
Absolutely! Under the "Watch" option in the upper right navigation, you can choose "Releases Only" to GItHub and email notifications when new releases are cut. We'll also follow up on this ticket for you!

**Comment by jranson** [comment]
Hey @Dudesons we finally have the helm charts in tip top shape. We will proceed with the HelmHub submission sometime next week and follow up again on this ticket when that process is completed. Thanks again for the suggestion!

**Comment by Dudesons** [comment]
Hi @jranson , oki good news 😄 
Since they announce helm 3, the helm hub will not be maintained (and will be marked as obsolete https://github.com/helm/charts/#status-of-the-project).
So maybe the chart have to be hosted in a github page like for [jaeger](https://github.com/jaegertracing/helm-charts/tree/gh-pages).

**Comment by jranson** [comment]
@Dudesons it looks like Helm Hub is not going away. What is going away is the `stable` and other repositories that are maintained directly by helm. So yeah - we will get our helm charts into a github pages like Jaeger _and_ get that listed on to Helm Hub. It looks like there is a little bit more process involved (getting the chart into a tarball, associating a SHA has with it, etc), that will require some automation; I will reach out to the Jaeger team and see if they have any guidance or scripts that we can adopt to Trickster, and hopefully we'll have this knocked out for you really soon!

**Comment by Dudesons** [comment]
Ok, awesome and thank you for your work :smiley:

**Comment by jranson** [comment]
@Dudesons we have the helm repo all setup and ready to go, just like Jaeger, right here on GitHub. We totally copied their repo - thanks for the tip ;-)  You can check out [our new Helm project](https://github.com/tricksterproxy/helm-charts) and our new repository at https://helm.tricksterproxy.io

We will have the PR submitted for this to be on Helm Hub in the next 24 hours, and as soon as that is merged, I'll close out this issue. Thanks for your patience while we got it all worked out!

**Comment by jranson** [comment]
We are live on helm hub at <https://hub.helm.sh/charts/trickster>   Thanks again for the suggestion!
