### ISSUE TITLE
Support for configuring Redis key prefix for each origin

### ISSUE THREAD

**Issue by elcomtik** [Comcast/trickster#329]
I'm interested in HA trickster setup with Redis cache backend like it's mentioned in https://github.com/Comcast/trickster/issues/214

I would like to have redundant thanos setup instead of one prometheus instance, so I would appreciate possibility to configure key prefix instead of using origin(prometheus) hostname.

I didn't find such option in 1.09, would such solution be acceptable by project?

**Comment by jranson** [comment]
@elcomtik Thanks for the feedback! I think it would be a great addition to allow for a custom cache key prefix, and should be fairly simple. We will implement this soon and update this issue when it is ready in beta 10.

**Comment by elcomtik** [comment]
Thanks for quick response a implementing it so quickly. I will wait for release and then test it in my setup.

**Comment by jranson** [comment]
@elcomtik this feature has been included in Beta 10, which is now live! Thank you for the feedback, and please re-open the issue i fit does not meet your needs.
