### ISSUE TITLE
Support for Arm64v8

### ISSUE THREAD

**Issue by jorkzijlstra** [Comcast/trickster#340]
Are there any plans for a arm64v8 based docker image?

Regards, Jork

**Comment by jranson** [comment]
@jorkzijlstra we did not have any plans to do that, but it's pretty simple, so we'll get it wired up for the next release!

**Comment by jranson** [comment]
@jorkzijlstra we are not able to get this into the current release (coming out in the next 30 minutes). We are working on getting Trickster into the "official" docker hub images, and when we do that, the process for multiple, per-architecture images is different. So as to avoid any confusion, we want to wait until the official process is completed. It should be in the next few weeks. Hope that is ok, and sorry for the delay!

**Comment by jorkzijlstra** [comment]
Hi @jranson no problem, take as much as you need.

**Comment by jranson** [comment]
@jorkzijlstra we have this ready to go in 1.0.0-rc2, image is available for arm64v8 at `tricksterio/trickster:arm64v8-1.0`. Thanks for the great feature request!

**Comment by jorkzijlstra** [comment]
I just gave it a go and it seems to work fine. Thnx for the quick work.

**Comment by jranson** [comment]
Glad to hear it!  Once Docker has our Official Image pipeline completed, you'll be able to pull the main tag; it will determine your architecture and send down the appropriate image. We didn't get that quite set up in time for the 1.0 main release, but I will comment here when all of that is worked out!
