### ISSUE TITLE
Logging not working when starting trickster as systemd service

### ISSUE THREAD

**Issue by chicknsoup** [Comcast/trickster#376]
When running as commandline: /opt/trickster/trickster -config /opt/trickster/trickster.conf the logging function is working properly. But when configuring trickster to run as systemd service, no log written to file.

Systemd configuration:

```
[Unit]
Description=Prometheus Trickster Service
After=network-online.target
Restart=always
RestartSec=90
StartLimitInterval=400
StartLimitBurst=3
[Service]
User=bigmon
ExecStart=/opt/rickster/trickster -config /opt/trickster/trickster.conf

[Install]
WantedBy=multi-user.target
Alias=prometheus-trickster.service
```

**Comment by jranson** [comment]
Thanks for this report. We'll take a look, but initial thoughts are to make sure you have the right ownership and access permissions on your log file (looks like it should be owned by `bigmon` user in the provided setup). If you are able to run it from the command line, is it possible that is being done with a different user account? If so, that would likely prevent the `bigmon` user from having write access.

**Comment by chicknsoup** [comment]
The process being executed with `bigmon` user, and the logging part works well with that, so no permissions issue here.

**Comment by jranson** [comment]
Thanks for the additional info! We are just getting started on restructuring the logging in #342 and will take a look at this as part of that effort.

**Comment by jranson** [comment]
@chicknsoup taking a look now, i see there is a typo in your ExecStart (missing the t on trickster). Can you let me know if that makes a difference in your tests? I will test on our side with the typo corrected.

**Comment by jranson** [comment]
@chicknsoup we are not able to reproduce. I have attached our test harness for this issue, for you you to try as well. It takes a system from fresh install (I used an fresh AWS EC2 instance w/ Amazon Linux 2 AMI) to running trickster via systemd and properly logging
. Please let us know what you find. This tarball includes the systemd service file you provided above - with the typo fixed - along with a config file pointing to the log and a simple bash script to accomplish the end-to-end orchestration. 

[systemd-test.tar.gz](https://github.com/Comcast/trickster/files/4242178/systemd-test.tar.gz)

**Comment by chicknsoup** [comment]
@jranson Thanks. I have tried the service on another server and logging works as expected. So there could be something wrong with my old server, I think. We can close this for now.
