### ISSUE TITLE
what is rmiss, kmiss, phit?

### ISSUE THREAD

**Issue by infa-ddeore** [Comcast/trickster#390]
what is `rmiss`, `kmiss`, `phit` meaning in trickster metrics, this is from v0.1.x version metrics, not sure if newer version has something changed.

based on which value should we tweak trickster?

![image](https://user-images.githubusercontent.com/39782583/76589387-f48cbb80-650f-11ea-8a4e-09fd8a8780d5.png)

**Comment by jranson** [comment]
You can read about these values in the [metrics](https://github.com/Comcast/trickster/blob/master/docs/metrics.md) documentation (they're largely unchanged from 0.1 to 1.0). Here is some more detail:

`kmiss` means that the query requested by the browser was not in the Trickster cache. Once a query is requested and then added to the cache, subsequent requests can have a `hit` meaning all of the time ranges the browser requested were in cache; a `phit`, meaning some of the time ranges were in cache while others had to be requested from the origin and reconstituted; and `rmiss`, which means that the query has cached data, but none of the requested time ranges were in the cache yet, so the full range had to be requested from the origin and merged into the cached data set.

Trickster 0.1 is not nearly as efficient at caching data as 1.0 is, so it is hard to give you an idea of what to tweak, esp without more granular information about the cache hit rate by url. For a full explanation of the differences in caching between 0.1 and 1.0, see [this section](https://github.com/Comcast/trickster/blob/master/docs/new-changed-1.0.md#timeseries_retention_factor) of the 1.0 What's Changed document. 

Thanks for the questions, and let me know if this answers everything!

**Comment by infa-ddeore** [comment]
thx for the explanation

**Comment by infa-ddeore** [comment]
https://grafana.com/grafana/dashboards/5756 doesn't work with `1.0`, is there similar dashboard for newer trickster version?

**Comment by jranson** [comment]
While we did not create this dashboard, we're working on an updated version that will work with v1.1, which should be released in the next 3 weeks.
