### ISSUE TITLE
Question: Performance of trickster and memory usage

### ISSUE THREAD

**Issue by FUSAKLA** [Comcast/trickster#56]
Hi, we discussed this at the slack channel some time ago when I was deploying Trickster in our company and had some issues regarding memory usage and this leading to frequent OOM kills.

Since than I did not see anyone mentioning any bigger setups but now @SuperQ mentioned deploying it in GitLab so I'm wondering how is Trickster working for you? 

Would it be possible to share any performance data? 

Possibly we can take this to the [slack channel](https://gophers.slack.com/messages/C9VDJLYA2) 

Thank's for any info on this

**Comment by SuperQ** [comment]
Yet another slack channel, happy to talk about it on the official [#prometheus IRC/Riot channel](https://prometheus.io/community/).

**Comment by FUSAKLA** [comment]
Well Trickster performance is not Prometheus related actually, but ok will take it there.

Thanks
