### ISSUE TITLE
Support New Origin Type: Circonus / IronDB

### ISSUE THREAD

**Issue by jranson** [Comcast/trickster#6]
Dependent on #9 completion

**Comment by husobee** [comment]
@jranson: I was wondering if I could get more information related to this issue.  I believe I understand the spirit, in that we want to expand the proxy capability to include different types of origins.  

Currently, as I read through the code we are obviously only supporting one type currently, Prometheus.  The `PrometheusOriginConfig` type seems to contain all of the location specific origin information about the particular backend locations and options.  

Is the plan to expand this `PrometheusOriginConfig` to be an implementable interface, such as `OriginConfig`, that would have origin type specific methods which are to be called by the proxy handler functions?  Do you envision the origin type specific proxy transformations being within the origin type interface implementations?  Thanks in advance for helping me understand!

**Comment by jranson** [comment]
@husobee Yes, the idea is to interface the existing prometheus implementation (#9) so that all of these other origin types can easily be plugged in by simply conforming to that interface. I haven't looked into all of what is required beyond that, as it is going to be a huge undertaking. My apologies for not having the foresight to interface it from the start - I was just so excited to get it working with Prometheus!

**Comment by jranson** [comment]
@husobee A year later - we have the interfacing ready to go on the `next` branch, and the 1.0 codebase is a lot easier to comprehend and extend. In addition to supporting Prom you will also find InfluxDB support (`internal/proxy/influxdb`), which provides two good examples for extending support to IronDB if you are interested in giving it a go. I believe we have some Comcast personnel also looking at this, I will have them comment here on their efforts. Thanks!

**Comment by kamelkev** [comment]
Hi @jranson - we're pretty interested in this here at @circonus. We have some other staff who can help here, including @dhaifley and @cody271.

Can you please make the relevant introductions to your staff, and we can see how to proceed?

My interest level in this is pretty high. Maybe worth grabbing lunch to discuss if you're still here in Denver.

**Comment by jranson** [comment]
Implemented in #252 pending PR merge.

**Comment by jranson** [comment]
Circonus IRONdb support is now avaiable in Trickster 1.0 Beta 10. Thanks to @kamelkev and @dhaifley for this great contribution!

**Comment by kamelkev** [comment]
@jranson wonderful 👏 🎉
