### ISSUE TITLE
Requests to /api/v1/series are not cached correctly

### ISSUE THREAD

**Issue by cosmopetrich** [Comcast/trickster#66]
Thanks for your work on Trickster, it's made our dashboards a lot more pleasant to use.

Some of our Grafana dashboards use [label_values()](http://docs.grafana.org/features/datasources/prometheus/) to populate templating variables. That function calls [`/api/v1/series[]match={label_name}&start=...`](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers) and we've been seeing some strange behaviour when that endpoint is served by Trickster.

Trickster does not appear to use `match[]`/`start`/`end` in the cache key. Results for this endpoint are always cached with the key `{origin}/api/v1/series` regardless of what data is being requested from Prometheus.

This should be pretty easy to reproduce with any setup. I've been the simple docker-compose config in [this gist](https://gist.github.com/cosmopetrich/a7aa88bec0bc958b2f7f038f7e13ea76) to look into the issue.

```markdown
# Against trickster
$ curl -w '\n' -g 'http://localhost:8000/api/v1/series?match[]=prometheus_build_info'
{"status":"success","data":[{"__name__":"prometheus_build_info","branch":"HEAD","goversion":"go1.10.3","instance":"localhost:9090","job":"prometheus","revision":"188ca45bd85ce843071e768d855722a9d9dabe03","version":"2.3.1"}]}

# Against trickster
$ curl -w '\n' -g 'http://localhost:8000/api/v1/series?match[]=this_is_a_fake_key_that_does_not_exist'
{"status":"success","data":[{"__name__":"prometheus_build_info","branch":"HEAD","goversion":"go1.10.3","instance":"localhost:9090","job":"prometheus","revision":"188ca45bd85ce843071e768d855722a9d9dabe03","version":"2.3.1"}]}

# Against Prometheus directly
$ curl -w '\n' -g 'http://localhost:9090/api/v1/series?match[]=this_is_a_fake_key_that_does_not_exist'
{"status":"success","data":[]}
```

I was considering opening a PR, but I'm not sure of the best approach.

 - Should the cache be bypassed for any endpoint that Trickster is not specifically configured to handle, or should some ordered set of all `match[]` values be included in the cache key?
 - What about `start`/`end`? Those don't appear to be used for other cache keys. I imagine that's related to the step normalisation?

**Comment by SuperQ** [comment]
👍 I've seen this behavior as well.

I'm in favor of not caching explicitly handled API endpoints.

**Comment by SuperQ** [comment]
Yup, confirmed, our public dashboard now works correctly.

https://monitor.gitlab.net/dashboard/db/unicorn-controller

It would be good to add correct cashing of this API endpoint. :-)
