### ISSUE TITLE
Cache Prometheus /api/v1/series

### ISSUE THREAD

**Issue by SuperQ** [Comcast/trickster#73]
As discovered in https://github.com/Comcast/trickster/issues/66, Trickster does not correctly cache this API endpoint.

**Comment by jranson** [comment]
@SuperQ  Hey Ben, I am going take a look at some of these longstanding-but-easy issues this weekend. For this one, do you have a recommended length of time for caching the series endpoint? Are there any api endpoints that should also be supported? Thanks!

**Comment by SuperQ** [comment]
Looking at the metrics, we get very few `series` handler requests via Grafana. I would say that it's probably good to cache for at most 5 minutes by default. Users expect newly added series to show up quickly. But a 5 minute cache would be helpful to deal with abuse/storms.

The only endpoints used on our front-end service that seem to be used are query, query_range ,and series.

**Comment by jranson** [comment]
Implemented in `next` via #175
