### ISSUE TITLE
Error on parsing step parametr

### ISSUE THREAD

**Issue by FUSAKLA** [Comcast/trickster#74]
Hi, I upgraded Trickster to version `0.0.15` and getting errors in log

```
time=2018-07-06T23:15:14.30393302Z app=trickster caller=trickster/handlers.go:174 level=error event="error building request context" detail="failed to parse parameter \"step\" with value \"300s\": strconv.ParseInt: parsing \"300s\": invalid syntax"
```

I looked at he code and it strikes me that Trickster tries to parse the step parameter as an integer?
https://github.com/Comcast/trickster/blob/master/handlers.go#L423

According to Prometheus documentation of the range query API it should be `duration` 
https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries

But if I inspect requests send by the Prometheus UI itself it sets the `step` to `14` but Prometheus accepts also `14s` if I edit the request and resend it.

Those requests are sent by Grafana `5.1.3` and fails only for annotation queries. Graph queries are ok. Grafana probably sets the step value different way for annotations. 

It looks like Prometheus accepts both, integer and duration but trickster counts only with the integer value.

**Comment by juliusv** [comment]
Indeed, thanks. This was my screwup, I forgot that Prometheus also accepts the other format for step values (despite the fact that I probably introduced support for the other format in Prometheus back then). Will send a fix.

**Comment by juliusv** [comment]
Ah, it was just a `ParseInt()` before in Trickster, just that any parse errors were ignored :)

**Comment by juliusv** [comment]
Yeah, it's seconds. And yeah, probably should be documented.

**Comment by juliusv** [comment]
Fix at https://github.com/Comcast/trickster/pull/76

**Comment by FUSAKLA** [comment]
That was fast! Thanks for solving this.

I made PR for the Prometheus docs 
https://github.com/prometheus/prometheus/pull/4360
