### ISSUE TITLE
Fast Forward returns most recent data point when zooming into older data in Grafana

### ISSUE THREAD

**Issue by arsenakishev** [Comcast/trickster#86]
Currently, if fast forward is enabled, the most recent data is always stitched into the result matrix of a Grafana query. This becomes an issue when I want to look at older data by zooming in. Because fast forward returns the most recent value, the graph ends with an extra point that messes up the y-axis.

Example 1: Reading directly from a Prometheus datasource and zooming in.(Query: node_forks_total)
![image](https://user-images.githubusercontent.com/10782719/43489647-b0b9428e-94eb-11e8-8985-689d2491f7ca.png)

Example 2: Reading from Trickster and zooming in.(Query: node_forks_total)
![image](https://user-images.githubusercontent.com/10782719/43489702-e92dfcd6-94eb-11e8-9914-2aeea8739451.png)

Tell me what you think. If you have any questions I can explain further. 

I think I have a general idea of how to fix this. I would like to give it a shot if possible.

Thanks.

**Comment by arsenakishev** [comment]
Issue seems to be in the handlers.go file. Whenever the code checks if the query is made in realtime it doesn't convert the ```ctx.Time``` variable to milliseconds. 
Since the other variable(```RequestExtents.End```)  being used for comparison is in milliseconds the resulting difference becomes much higher than most step boundaries.

**Comment by jranson** [comment]
@arsenakishev Thanks for finding this and for the PR, looks like it indeed fixed this one up!
