### ISSUE TITLE
High memory usage with redis cache backend

### ISSUE THREAD

**Issue by stewrutledgebonnier** [Comcast/trickster#91]
We're using the redis cache backend in our instance of trickster and we're seeing suprisingly high memory usage.

We are running trickster in kubernetes, with memory limited to 4GB. Trickster only needs to be up for half an hour before it's killed for using more than 4GB memory (OOM).

Has anyone seen any similar behavior? Any idea what could be going on? We've tested increasing the memory limits, they were originally set to 2GB, but the problem persists.

**Comment by FUSAKLA** [comment]
Hi, what version do you use? 

I experienced the same behavior but since Julius fixe this
https://github.com/Comcast/trickster/pull/85

it's way more stable and works like a charm for me I have to say.

**Comment by stewrutledgebonnier** [comment]
I'm using version 0.1.1 (latest)

**Comment by stewrutledgebonnier** [comment]
Could it potentially be related to https://github.com/go-redis/redis/issues/832?

**Comment by FUSAKLA** [comment]
Ok, possibly try to use the BoltDB which could sort out the redis. Also what version of redis do you use?

**Comment by stewrutledgebonnier** [comment]
So far using the in memory cache has less of a memory footprint than using redis.

**Comment by SuperQ** [comment]
Here's a profile on BoltDB
[heap.svg.gz](https://github.com/Comcast/trickster/files/2511537/heap.svg.gz)

**Comment by SuperQ** [comment]
@juliusv and I worked up a patch that closes the cache goroutines after they've been idle for 10 seconds. This seems to help greatly with our setup.

https://github.com/juliusv/trickster/commit/b2b82c862932282a32300b4ba279d62500642250

https://dashboards.gitlab.com/dashboard/snapshot/pvDNQsfFnzc9pxE6uuTZ0FNUG2BpjA7j

We went from several hundred thousand open FDs and goroutines and GB of memory to under 1k goroutines and a few hundred MB of memory.

**Comment by SuperQ** [comment]
Yup, I'll get the new version into testing soon.

**Comment by SuperQ** [comment]
I've started 0.1.4 in production. Will see how it behaves over the next day or so.

**Comment by SuperQ** [comment]
Getting a panic:

```
panic: runtime error: index out of range
goroutine 1815 [running]:
main.(*PrometheusMatrixEnvelope).cropToRange(0xc000253238, 0x5c07e3b2, 0x0)
#011/Users/jranso000/code/go/src/github.com/Comcast/trickster/handlers.go:1035 +0x4ee
main.(*TricksterHandler).originRangeProxyHandler(0xc000132300, 0xc000d43310, 0x41, 0xc000e25a40)
#011/Users/jranso000/code/go/src/github.com/Comcast/trickster/handlers.go:860 +0x6b4
created by main.(*TricksterHandler).queueRangeProxyRequest
#011/Users/jranso000/code/go/src/github.com/Comcast/trickster/handlers.go:660 +0x276
```

**Comment by sylr** [comment]
@SuperQ #105

**Comment by SuperQ** [comment]
I've switched our Trickster over to memory cache, just to see how it behaves.

I'm seeing a very strange memory leaking pattern.

https://dashboards.gitlab.com/dashboard/snapshot/C8bIw0RsFx4nhw7HSkVvMOjUw3B0WbPK

https://dashboards.gitlab.com/dashboard/snapshot/wyINL7CX8tnwVSb3ES0xPPV9hYYMRsmy

The heap growth follows the traffic pattern, but the memory use climbs and climbs over time, I'm going to try and capture some heap SVGs to see if I can figure out where it's all going.

**Comment by jranson** [comment]
All, a very astute finding by @arsenakishev in #118 was that the Reaper background goroutine was not being started for Redis caches and has been merged into master. This could potentially have been impacting this High Memory issue. Would anyone experiencing this issue be able to test against master let us know if that resolves this? If needed, I am happy to spin up a release candidate docker image to pull.

**Comment by jranson** [comment]
All of the reports for this issue are related to the legacy codebase and releases which, as of today, are no longer supported. If you are experiencing this issue in Trickster 1.0, please open a new issue and we will take a fresh look at it.
